* nixos-config

** During NixOS installation

Before ~nixos-install~, use ~initial_configuration.nix~ as configuration.nix (enables networking and sets up basic user). After ~nixos-install~, set a password for user ~tim~:

#+begin_src sh
$ passwd tim
#+end_src

** From new NixOS installation
How to login to GitHub? Using "gh" is an option. HTTPS better than SSH?
#+begin_src sh
$ git clone git@github.com:SlimTim10/nixos-config.git /home/tim/.nix-config
$ git clone git@github.com:SlimTim10/emacs-home.git /home/tim/emacs-home
$ cd ~/.nix-config
$ cp hardware.nix.example hardware.nix
$ ./nixos-rebuild.sh
#+end_src

** Auto mount USB external drive
#+begin_src sh
$ sudo fdisk -l # find the drive
$ sudo mkdir -p /mnt/external-hdd
$ sudo mount -t ntfs -o umask=000 /dev/sda1 /mnt/external-hdd # for NTFS-formatted drive, full R/W permission (-o umask=000 may not be needed since adding support for NTFS)
$ sudo mkdir -p /mnt/external-ssd
$ sudo mount -t ntfs -o umask=000 /dev/sdb2 /mnt/external-ssd
$ sudo nixos-generate-config # updates /etc/nixos/hardware-configuration.nix
#+end_src

** Storage management (garbage collection)
You can remove all but the current generation with

#+begin_src sh
$ sudo nix-collect-garbage -d
#+end_src

There are also user-specific generations for different things (eg. home-manager). These can be removed with

#+begin_src sh
$ nix-collect-garbage -d
#+end_src

More info
- https://nixos.wiki/wiki/Storage_optimization
- https://nixos.org/manual/nix/stable/#sec-garbage-collection

** File organization

General configuration is in ~configuration.nix~.

...

** Installing and removing packages (programs)

https://search.nixos.org/packages

3 different ways:

1. Permanent
   Add to packages.nix

2. Ephemeral
   [tim@nixos:~]$ nix-shell -p tty-solitaire
   [nix-shell:~]$ ttysolitaire
   [nix-shell:~]$ exit
   [tim@nixos:~]$ nix-collect-garbage

3. Global
(DON'T USE THIS)
nix-env -iA nixos.tty-solitaire
Deleting:
nix-store --query --roots /nix/store/17rr89knzpnk3hg3cb8fw63qw5lglqxk-tty-solitaire-1.3.1.drv
sudo nix store delete /nix/store/17rr89knzpnk3hg3cb8fw63qw5lglqxk-tty-solitaire-1.3.1

** Navigation

...

** Networking

Use nmtui (or nmcli) from command line

** Android file transfer

Use ~jmtpfs~ to mount the device, then use ~rsync~ as root.

#+begin_src
$ su
# nix-shell -p jmtpfs
# jmtpfs /media
# cd "/media/Internal shared storage/DCIM/Camera"
# rsync -avhP --ignore-existing IMG_2022* /mnt/external-hdd/Photos\ and\ Videos/2022/misc/
# rsync -avhP --ignore-existing VID_2022* /mnt/external-hdd/Photos\ and\ Videos/2022/misc/
#+end_src

See https://nixos.wiki/wiki/MTP.

** Backup files

Sync drives, deleting files in destination that are not in source.

#+begin_src
$ sudo mount /dev/sdc1 /media/
$ git clone git@github.com:SlimTim10/nixos-config.git /media/.nix-config
$ cd /media/.nix-config
$ git pull
$ git clone git@github.com:SlimTim10/emacs-home.git /media/emacs-home
$ cd /media/emacs-home
$ git pull
$ rsync -avhPW --delete --compress-level=0 /mnt/external-hdd/ /media/data/
$ rsync -avhPW --delete --compress-level=0 /home/tim/Dropbox/ /media/Dropbox/
$ sudo rsync -avhPW --delete --compress-level=0 /home/tim/Dropbox/ /mnt/external-ssd/Dropbox/
#+end_src
